### ISSUE TITLE
fails to create masking job for "on the fly" option

### ISSUE THREAD

**Issue by santy197118** [delphix/dxm-toolkit#18]
Will return below error
This OnTheFly MaskingJob needs a source File Connector specified.

Example:  ./dxmc job add --jobname API-BC_TACCOUNT --envname AwsMask-Target --rulesetname API-BC_TACCOUNT --on_the_fly_source SOURCE-BC_TACCOUNT --max_memory 8192 --min_memory 4096 --num_streams 20 --on_the_fly Y

**Comment by pioro** [comment]
fixed in 0.52
