### ISSUE TITLE
"05/23/2021 Unable to create OTF job

### ISSUE THREAD

**Issue by ajaytho** [delphix/dxm-toolkit#52]
** Expected Behavior**
Create OTF job

** Actual Behavior**
EXCEPTION: ValueError: Invalid value for `connector_id`, must not be `None`

**Steps To Reproduce the Problem**
```
./dxmc connector test --engine mymskengine --connectorname orasrc_conn                                                                                                         
Connector test orasrc_conn succeeded
./dxmc job add --jobname maskjob7 --engine mymskengine --envname mskdevenv --rulesetname myruleset2 --max_memory 2048 --min_memory 2048 --num_streams 1 --on_the_fly Y --on_the_fly_src_connector orasrc_conn --on_the_fly_src_envname mskprdenv
```
EXCEPTION: ValueError: Invalid value for `connector_id`, must not be `None`
[13101] Failed to execute script dxmc

**Version**
version 0.8.2.1

**Comment by marcinops** [comment]
fixed in develop - it will be released with next release
